# Generated by Django 5.1 on 2024-08-11 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='почта')),
                ('country', models.CharField(max_length=60, verbose_name='город')),
                ('city', models.CharField(max_length=60, verbose_name='город')),
                ('street', models.CharField(max_length=60, verbose_name='город')),
                ('house', models.CharField(max_length=10, verbose_name='город')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('model', models.CharField(max_length=150, verbose_name='модель')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('type', models.CharField(choices=[('0', 'завод'), ('1', 'розничная сеть'), ('2', 'индивидуальный предприниматель')], default=1, max_length=1, verbose_name='тип')),
                ('debt', models.BooleanField(verbose_name='задолженность перед поставщиком')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='provider.contact', verbose_name='контакты')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.product', verbose_name='продукты')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.provider', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
            },
        ),
    ]
