# Generated by Django 5.1 on 2024-08-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(max_length=60, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='house',
            field=models.CharField(max_length=10, verbose_name='дом'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(max_length=60, verbose_name='улица'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='debt',
            field=models.BooleanField(blank=True, default=0.0, null=True, verbose_name='задолженность перед поставщиком'),
        ),
    ]
