# Generated by Django 5.1 on 2024-08-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_remove_provider_debt_remove_provider_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='debt',
            field=models.FloatField(default=0, verbose_name='задолженность перед поставщиком'),
        ),
    ]
