# Generated by Django 5.1 on 2024-08-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_provider_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('завод', 'завод'), ('розничная сеть', 'розничная сеть'), ('ип', 'индивидуальный предприниматель')], default='завод', max_length=20, verbose_name='тип'),
        ),
    ]
